tdewolff:
  css:
    inline: false
    precision: 0
    version: 0
  html:
    keepDefaultAttrVals: true
    keepDocumentTags: true
    keepEndTags: true
    keepSpecialComments: true
    templateDelims:
      - ''
      - ''
  js:
    version: 2022
  json: {}
  svg: {}
  xml: {}
