actionsPanel:
  disabled: true
archive:
  paginate: 20 ### Archive pagination. Default to 100.
  # basePath = "/archiv"  ### The base path of archive pages.
  # dateFormat: 01-02     ### Archive date format. Default to Jan 2.
author:
  avatar: images/OnIT-noborder.png
  bio: "PowerShell documentarian"
  company: Microsoft
  location: "Denton, TX"
  name: Sean D. Wheeler
  params:
    layout: compact
  social:
    # email: swsamwa@live.com
    # mastodon: https://sdwheeler@fosstodon.org
    bluesky: https://bsky.app/profile/sdwheeler.bsky.social
    github: https://github.com/sdwheeler
    linkedin: https://linkedin.com/in/scriptingsean
    rss: "" # Remove RSS
    sessionize: https://sessionize.com/sean-wheeler
    stickermule: https://www.stickermule.com/sdwheeler
    x-twitter: https://x.com/swsamwa
brand: Sean on IT
breadcrumb: true
carouselPostCount: 5
codeblock:
  #maxLines: 50
  lineNos: true
color: light ### light, dark or auto. Default to auto.
comment: true ### Toggle comment widget on/off
countTaxonomyPosts: true
#customCSS:
#  - css/main.css
dateFormat: 2026-01-01 ## Possible values - https://gohugo.io/functions/time/format/
description: Sharing the things I have learned in my IT journey.
docs:
  copyright: false ### Whether to display copyright section on each post.
  featuredImage: true ### Show the featured image above the content.
  numberifyHeadings: false ### Count headings automatically.
  tocStyleType: disc ### The TOC's CSS list-style-type property.
  # excerpt: description
  # excerptMaxLength: 120
  # plainifyExcerpt: false ### Format excerpt in HTML if false.
  # numberifyHeadingsEndLevel: 4 ### The depth of headings to count. Default to 6.
  # numberifyHeadingsSeparator: . ### The separator between of number and headings.
  # imageTitleAsCaption: true
  # panel: false
  # nav: false
  # readMoreFromContent: true
  ### The page position after clicking the read more button, read more from content if true.
  ### Default to the beginning of page. Supports manual summary splitting via <!--more-->.
favicon:
  sizes:
    - size: 16x16
    - size: 32x32
    - size: 150x150
    - rel: apple-touch-icon
      size: 180x180
    - size: 192x192
featuredPostCount: 5
feeds:
  content: true
fixedHeader: true
fontSize:
  extraLarge: 1.2rem
  extraSmall: .8rem
  large: 1.1rem
  small: .9rem
giscus:
  repo: sdwheeler/seanonit
  repo-id: R_kgDOKHe1gw
  category: Site comments
  category-id: DIC_kwDOKHe1g84ClEjV
  mapping: og:title
  strict: 1
  reactions-enabled: 1
  emit-metadata: 0
  input-position: bottom
  theme: cobalt
  lang: en
  loading: lazy
contact:
  endpoint: https://forms.un-static.com/forms/0a549d00d00f09c262ebdd17977d004558de66d0
  reCaptcha:
    siteKey: 6LcoBq4rAAAAACz1lPeciF5dErcHPHbzQd-hMBJh
keywords: PowerShell, technical writing
logo: images/OnIT.png
mainSections:
  - blog
  - posts ### Default is 'posts'
  # - docs    ### Adding 'docs' puts docs in the main page list
metaRobots: index, follow ### Empty value disables Meta Tag robots
palette: blue
palettes: false
#  - blue
#  - blue gray
#  - brown
#  - cyan
#  - green
#  - indigo
#  - orange
#  - pink
#  - purple
#  - red
#  - teal
#  - yellow
pinnedPost: true
pinnedPostCount: 3
post:
  # excerptMaxLength: 120
  copyright: false
  excerpt: description
  plainifyExcerpt: false   ### Format excerpt in HTML if false.
  featuredImage: true ### Show the featured image above the content.
  numberifyHeadings: false ### Count headings automatically.
  tocStyleType: disc ### The TOC's CSS list-style-type property. See https://www.w3schools.com/cssref/pr_list-style-type.php
  # imageTitleAsCaption: true
  # panel: false
  # nav: false
  ### The page position after clicking the read more button, read more from content if true.
  ### Default to the beginning of page.
  ### Support manual summary splitting via <!--more-->.
  # readMoreFromContent: true
postdate: true
poweredBy: true
readingTime: false
recentPostCount: 0
relatedPostCount: false ### The number of related posts.
repo:
  branch: main
  url: https://github.com/sdwheeler/seanonit
  # subPath: exampleSite
  dateFormat: 2026-01-01
rss: home
sass_transpiler: dartsass
search:
  resultContentWordCount: 240 ### 240 maximum word count of result display
  # Fuse.js options. See https://fusejs.io/api/options.html.
  fuse:
    ignoreLocation: true
    location: 0
    includeScore: true
    isCaseSensitive: false
    minMatchCharLength: 3
    threshold: 0.1
    distance: 5
    shouldSort: true
    useExtendedSearch: true
  paginate: 10 ### Pagination. Default to 10.
searchBar: true
sidebar:
  # archives: true
  # taxonomiesToggle: false
  # categories: true
  # tags: true
  # series: true
  authors: true
  collapsed: true
  postsToggle: true
  featuredPosts: false
  fixed: false
  recentPosts: false
sidebarTaxonomies:
  - categories
  - tags
  - series
social:
  # mastodon: https://sdwheeler@fosstodon.org
  bluesky: https://bsky.app/profile/sdwheeler.bsky.social
  github: https://github.com/sdwheeler
  linkedin: https://linkedin.com/in/scriptingsean
  sessionize: https://sessionize.com/sean-wheeler
  stickermule: https://www.stickermule.com/sdwheeler
  x-twitter: https://x.com/swsamwa
taxonomyPaginate: 10
taxonomyPostCount: 20
titleCase: true
titleSeparator: "-"
tocPosition: sidebar
tocWordCount: 208 # TOC is displayed only if the post's word count exceeds this value.
topAppBar:
  coloredInDark: true
  dropdownMenuToggle: true
  social:
    # mastodon: https://sdwheeler@fosstodon.org
    bluesky: https://bsky.app/profile/sdwheeler.bsky.social
    github: https://github.com/sdwheeler
    linkedin: https://linkedin.com/in/scriptingsean
    sessionize: https://sessionize.com/sean-wheeler
    stickermule: https://www.stickermule.com/sdwheeler
    x-twitter: https://x.com/swsamwa
viewer: true
